spring:
    application:
        name: config

    cloud:
        config:
            server:
                git: 
                    uri: https://github.com/NRuslanR/Java/tree/master/Examples/Spring/TacoCloud/configserver

server:
    port: 8888