spring:
    application:
        name: config

    cloud:
        config:
            server:
                git: 
                    uri: https://github.com/NRuslanR/tacocloud-config

server:
    port: 8888