// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

/**
 * Protobuf type {@code org.grpc_learning.CreateTodoItemResponse}
 */
public  final class CreateTodoItemResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.grpc_learning.CreateTodoItemResponse)
    CreateTodoItemResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTodoItemResponse.newBuilder() to construct.
  private CreateTodoItemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTodoItemResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTodoItemResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateTodoItemResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.grpc_learning.TodoItemDto.Builder subBuilder = null;
            if (createdTodoItem_ != null) {
              subBuilder = createdTodoItem_.toBuilder();
            }
            createdTodoItem_ = input.readMessage(org.grpc_learning.TodoItemDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdTodoItem_);
              createdTodoItem_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.grpc_learning.TodoService.internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.grpc_learning.TodoService.internal_static_org_grpc_learning_CreateTodoItemResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.grpc_learning.CreateTodoItemResponse.class, org.grpc_learning.CreateTodoItemResponse.Builder.class);
  }

  public static final int CREATEDTODOITEM_FIELD_NUMBER = 1;
  private org.grpc_learning.TodoItemDto createdTodoItem_;
  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   * @return Whether the createdTodoItem field is set.
   */
  public boolean hasCreatedTodoItem() {
    return createdTodoItem_ != null;
  }
  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   * @return The createdTodoItem.
   */
  public org.grpc_learning.TodoItemDto getCreatedTodoItem() {
    return createdTodoItem_ == null ? org.grpc_learning.TodoItemDto.getDefaultInstance() : createdTodoItem_;
  }
  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   */
  public org.grpc_learning.TodoItemDtoOrBuilder getCreatedTodoItemOrBuilder() {
    return getCreatedTodoItem();
  }

  public static final int CREATEDAT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   * @return Whether the createdAt field is set.
   */
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   * @return The createdAt.
   */
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (createdTodoItem_ != null) {
      output.writeMessage(1, getCreatedTodoItem());
    }
    if (createdAt_ != null) {
      output.writeMessage(2, getCreatedAt());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (createdTodoItem_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreatedTodoItem());
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreatedAt());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.grpc_learning.CreateTodoItemResponse)) {
      return super.equals(obj);
    }
    org.grpc_learning.CreateTodoItemResponse other = (org.grpc_learning.CreateTodoItemResponse) obj;

    if (hasCreatedTodoItem() != other.hasCreatedTodoItem()) return false;
    if (hasCreatedTodoItem()) {
      if (!getCreatedTodoItem()
          .equals(other.getCreatedTodoItem())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCreatedTodoItem()) {
      hash = (37 * hash) + CREATEDTODOITEM_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedTodoItem().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.grpc_learning.CreateTodoItemResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.grpc_learning.CreateTodoItemResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.grpc_learning.CreateTodoItemResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.grpc_learning.CreateTodoItemResponse)
      org.grpc_learning.CreateTodoItemResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.grpc_learning.TodoService.internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.grpc_learning.TodoService.internal_static_org_grpc_learning_CreateTodoItemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.grpc_learning.CreateTodoItemResponse.class, org.grpc_learning.CreateTodoItemResponse.Builder.class);
    }

    // Construct using org.grpc_learning.CreateTodoItemResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (createdTodoItemBuilder_ == null) {
        createdTodoItem_ = null;
      } else {
        createdTodoItem_ = null;
        createdTodoItemBuilder_ = null;
      }
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.grpc_learning.TodoService.internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor;
    }

    @java.lang.Override
    public org.grpc_learning.CreateTodoItemResponse getDefaultInstanceForType() {
      return org.grpc_learning.CreateTodoItemResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.grpc_learning.CreateTodoItemResponse build() {
      org.grpc_learning.CreateTodoItemResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.grpc_learning.CreateTodoItemResponse buildPartial() {
      org.grpc_learning.CreateTodoItemResponse result = new org.grpc_learning.CreateTodoItemResponse(this);
      if (createdTodoItemBuilder_ == null) {
        result.createdTodoItem_ = createdTodoItem_;
      } else {
        result.createdTodoItem_ = createdTodoItemBuilder_.build();
      }
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.grpc_learning.CreateTodoItemResponse) {
        return mergeFrom((org.grpc_learning.CreateTodoItemResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.grpc_learning.CreateTodoItemResponse other) {
      if (other == org.grpc_learning.CreateTodoItemResponse.getDefaultInstance()) return this;
      if (other.hasCreatedTodoItem()) {
        mergeCreatedTodoItem(other.getCreatedTodoItem());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.grpc_learning.CreateTodoItemResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.grpc_learning.CreateTodoItemResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.grpc_learning.TodoItemDto createdTodoItem_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.grpc_learning.TodoItemDto, org.grpc_learning.TodoItemDto.Builder, org.grpc_learning.TodoItemDtoOrBuilder> createdTodoItemBuilder_;
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     * @return Whether the createdTodoItem field is set.
     */
    public boolean hasCreatedTodoItem() {
      return createdTodoItemBuilder_ != null || createdTodoItem_ != null;
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     * @return The createdTodoItem.
     */
    public org.grpc_learning.TodoItemDto getCreatedTodoItem() {
      if (createdTodoItemBuilder_ == null) {
        return createdTodoItem_ == null ? org.grpc_learning.TodoItemDto.getDefaultInstance() : createdTodoItem_;
      } else {
        return createdTodoItemBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public Builder setCreatedTodoItem(org.grpc_learning.TodoItemDto value) {
      if (createdTodoItemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdTodoItem_ = value;
        onChanged();
      } else {
        createdTodoItemBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public Builder setCreatedTodoItem(
        org.grpc_learning.TodoItemDto.Builder builderForValue) {
      if (createdTodoItemBuilder_ == null) {
        createdTodoItem_ = builderForValue.build();
        onChanged();
      } else {
        createdTodoItemBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public Builder mergeCreatedTodoItem(org.grpc_learning.TodoItemDto value) {
      if (createdTodoItemBuilder_ == null) {
        if (createdTodoItem_ != null) {
          createdTodoItem_ =
            org.grpc_learning.TodoItemDto.newBuilder(createdTodoItem_).mergeFrom(value).buildPartial();
        } else {
          createdTodoItem_ = value;
        }
        onChanged();
      } else {
        createdTodoItemBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public Builder clearCreatedTodoItem() {
      if (createdTodoItemBuilder_ == null) {
        createdTodoItem_ = null;
        onChanged();
      } else {
        createdTodoItem_ = null;
        createdTodoItemBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public org.grpc_learning.TodoItemDto.Builder getCreatedTodoItemBuilder() {
      
      onChanged();
      return getCreatedTodoItemFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    public org.grpc_learning.TodoItemDtoOrBuilder getCreatedTodoItemOrBuilder() {
      if (createdTodoItemBuilder_ != null) {
        return createdTodoItemBuilder_.getMessageOrBuilder();
      } else {
        return createdTodoItem_ == null ?
            org.grpc_learning.TodoItemDto.getDefaultInstance() : createdTodoItem_;
      }
    }
    /**
     * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.grpc_learning.TodoItemDto, org.grpc_learning.TodoItemDto.Builder, org.grpc_learning.TodoItemDtoOrBuilder> 
        getCreatedTodoItemFieldBuilder() {
      if (createdTodoItemBuilder_ == null) {
        createdTodoItemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.grpc_learning.TodoItemDto, org.grpc_learning.TodoItemDto.Builder, org.grpc_learning.TodoItemDtoOrBuilder>(
                getCreatedTodoItem(),
                getParentForChildren(),
                isClean());
        createdTodoItem_ = null;
      }
      return createdTodoItemBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.grpc_learning.CreateTodoItemResponse)
  }

  // @@protoc_insertion_point(class_scope:org.grpc_learning.CreateTodoItemResponse)
  private static final org.grpc_learning.CreateTodoItemResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.grpc_learning.CreateTodoItemResponse();
  }

  public static org.grpc_learning.CreateTodoItemResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTodoItemResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateTodoItemResponse>() {
    @java.lang.Override
    public CreateTodoItemResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateTodoItemResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateTodoItemResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTodoItemResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.grpc_learning.CreateTodoItemResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

