// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

public interface CreateTodoItemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.grpc_learning.CreateTodoItemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   * @return Whether the createdTodoItem field is set.
   */
  boolean hasCreatedTodoItem();
  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   * @return The createdTodoItem.
   */
  org.grpc_learning.TodoItemDto getCreatedTodoItem();
  /**
   * <code>.org.grpc_learning.TodoItemDto createdTodoItem = 1;</code>
   */
  org.grpc_learning.TodoItemDtoOrBuilder getCreatedTodoItemOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
