// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

public interface CreateTodoItemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.grpc_learning.CreateTodoItemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
