// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

public final class TodoService {
  private TodoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_grpc_learning_CreateTodoItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_grpc_learning_CreateTodoItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_grpc_learning_TodoItemDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_grpc_learning_TodoItemDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_grpc_learning_CreateTodoItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TodoService.proto\022\021org.grpc_learning\032\037" +
      "google/protobuf/timestamp.proto\":\n\025Creat" +
      "eTodoItemRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013descri" +
      "ption\030\002 \001(\t\"\240\001\n\013TodoItemDto\022\n\n\002id\030\001 \001(\004\022" +
      "\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\0221\n\006st" +
      "atus\030\004 \001(\0162!.org.grpc_learning.TodoItemS" +
      "tatus\022/\n\013performedAt\030\005 \001(\0132\032.google.prot" +
      "obuf.Timestamp\"\200\001\n\026CreateTodoItemRespons" +
      "e\0227\n\017createdTodoItem\030\001 \001(\0132\036.org.grpc_le" +
      "arning.TodoItemDto\022-\n\tcreatedAt\030\002 \001(\0132\032." +
      "google.protobuf.Timestamp*=\n\016TodoItemSta" +
      "tus\022\016\n\nPerforming\020\000\022\r\n\tPerformed\020\001\022\014\n\010Re" +
      "jected\020\0022x\n\017TodoItemService\022e\n\016createTod" +
      "oItem\022(.org.grpc_learning.CreateTodoItem" +
      "Request\032).org.grpc_learning.CreateTodoIt" +
      "emResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_grpc_learning_CreateTodoItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_grpc_learning_CreateTodoItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_grpc_learning_CreateTodoItemRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_org_grpc_learning_TodoItemDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_grpc_learning_TodoItemDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_grpc_learning_TodoItemDto_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Status", "PerformedAt", });
    internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_grpc_learning_CreateTodoItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_grpc_learning_CreateTodoItemResponse_descriptor,
        new java.lang.String[] { "CreatedTodoItem", "CreatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
