// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

/**
 * Protobuf enum {@code org.grpc_learning.TodoItemStatus}
 */
public enum TodoItemStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Performing = 0;</code>
   */
  Performing(0),
  /**
   * <code>Performed = 1;</code>
   */
  Performed(1),
  /**
   * <code>Rejected = 2;</code>
   */
  Rejected(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Performing = 0;</code>
   */
  public static final int Performing_VALUE = 0;
  /**
   * <code>Performed = 1;</code>
   */
  public static final int Performed_VALUE = 1;
  /**
   * <code>Rejected = 2;</code>
   */
  public static final int Rejected_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TodoItemStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TodoItemStatus forNumber(int value) {
    switch (value) {
      case 0: return Performing;
      case 1: return Performed;
      case 2: return Rejected;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TodoItemStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TodoItemStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TodoItemStatus>() {
          public TodoItemStatus findValueByNumber(int number) {
            return TodoItemStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.grpc_learning.TodoService.getDescriptor().getEnumTypes().get(0);
  }

  private static final TodoItemStatus[] VALUES = values();

  public static TodoItemStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TodoItemStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.grpc_learning.TodoItemStatus)
}

