// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TodoService.proto

package org.grpc_learning;

public interface TodoItemDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.grpc_learning.TodoItemDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.org.grpc_learning.TodoItemStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.org.grpc_learning.TodoItemStatus status = 4;</code>
   * @return The status.
   */
  org.grpc_learning.TodoItemStatus getStatus();

  /**
   * <code>.google.protobuf.Timestamp performedAt = 5;</code>
   * @return Whether the performedAt field is set.
   */
  boolean hasPerformedAt();
  /**
   * <code>.google.protobuf.Timestamp performedAt = 5;</code>
   * @return The performedAt.
   */
  com.google.protobuf.Timestamp getPerformedAt();
  /**
   * <code>.google.protobuf.Timestamp performedAt = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPerformedAtOrBuilder();
}
